<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nt</string>
	</array>
	<key>name</key>
	<string>N-Triples</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>URI</string>
			<key>match</key>
			<string>&lt;[^&lt;&gt;"{}|^`\]\\]*&gt;</string>
			<key>name</key>
			<string>string.uri.ntriples</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.ntriples</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ntriples</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.ntriples</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Typed literal</string>
			<key>match</key>
			<string>("[^"]*")(\^\^)(&lt;[^&lt;&gt;"{}|^`\]\\]*&gt;|\w*:[^\s)]+)</string>
			<key>name</key>
			<string>literal.ntriples</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.sparql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.sparql</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Blank node</string>
			<key>match</key>
			<string>(_:)([^\s]+)</string>
			<key>name</key>
			<string>constant.complex.sparql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.ntriples</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ntriples</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.ntriples</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String literal</string>
			<key>match</key>
			<string>("(?:(?:[^\x22\x5C\xA\xD])|\\[tbnrf\"'])*")(@[a-zA-Z-]+)?</string>
			<key>name</key>
			<string>constant.other.ntriples</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.sparql</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ntriples</string>
	<key>uuid</key>
	<string>f382d2fb-f67f-44c2-a190-83d7298960d9</string>
</dict>
</plist>
